#-----------------------------------------
# CloudBuild Pipeline for Prod CloudRun
#-----------------------------------------
steps:
# Docker Build Image
  - name: gcr.io/cloud-builders/docker
    id  : BUILD
    args: ['build', '-t', '$_SERVICE_IMAGE', '.', '-f', 'Dockerfile']

# Docker Push Image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id  : PUSH
    args: ['push', '$_SERVICE_IMAGE']

# Docker Deploy image to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    id  : DEPLOY
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - --project=$_SERVICE_PROJECT
      - --region=$_SERVICE_REGION
      - --image=$_SERVICE_IMAGE

images: # Display the image in the build results - Build Artifacts
- $_SERVICE_IMAGE

substitutions:
    _SERVICE_IMAGE    : ${_SERVICE_REGION}-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REGISTRY}/${_DOCKER_IMAGENAME}:${SHORT_SHA}
    _SERVICE_REGION   : europe-central2
    _SERVICE_PROJECT  : apt-achievment-372515
    _SERVICE_NAME     : my-docker-app-prod
    _DOCKER_REGISTRY  : chaus-test
    _DOCKER_IMAGENAME : myapp-prod
